# Generated by Django 4.1.2 on 2022-10-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_article_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sifgdfmage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.imagegallery', verbose_name='Раздел'),
        ),
    ]
