# Generated by Django 4.1.2 on 2022-10-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_sifgdfmage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sifgdfmage',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.imagegallery', verbose_name='Галлерея'),
        ),
    ]
