# Generated by Django 4.1.2 on 2022-10-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_sifgdfmage_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='gallery',
        ),
    ]
