# Generated by Django 4.1.2 on 2022-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_options_remove_product_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
    ]
