# Generated by Django 3.1.7 on 2022-11-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_article_image_delete_imagegallery'),
        ('shop', '0005_auto_20210414_1718'),
    ]

    operations = [
    ]
